name       : python-pytest-asyncio
version    : 0.10.0
release    : 2
source     :
    - https://github.com/pytest-dev/pytest-asyncio/archive/v0.10.0.tar.gz : 4a2f53fb40b8075739018e026bd0d3d2485d9f7c228974c817a6b43ed1350ed0
homepage   : https://github.com/pytest-dev/pytest-asyncio
license    : Apache-2.0
component  : programming.python
summary    : Pytest support for asyncio
description: |
    pytest-asyncio is an Apache2 licensed library, written in Python, for testing asyncio code with pytest. asyncio code is usually written in the form of coroutines, which makes it slightly more difficult to test using normal testing tools. pytest-asyncio provides useful fixtures and markers to make testing easier.
builddeps  :
    - python-async-generator
    - python-hypothesis
    - python-pytest
rundeps    :
    - python-pytest
#setup      : |
#    %patch -p1 < $pkgfiles/python-3.8.patch
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3
