name       : python-pytest-asyncio
version    : 0.20.3
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-asyncio/pytest-asyncio-0.20.3.tar.gz : 83cbf01169ce3e8eb71c6c278ccb0574d1a7a3bb8eaaf5e50e0ad342afb33b36
homepage   : https://github.com/pytest-dev/pytest-asyncio
license    : Apache-2.0
component  : programming.python
summary    : Pytest support for asyncio
description: |
    pytest-asyncio is an Apache2 licensed library, written in Python, for testing asyncio code with pytest. asyncio code is usually written in the form of coroutines, which makes it slightly more difficult to test using normal testing tools. pytest-asyncio provides useful fixtures and markers to make testing easier.
builddeps  :
    - python-async-generator # check
    - python-build
    - python-flaky           # check
    - python-hypothesis      # check
    - python-installer
    - python-pytest          # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # we don't have python-pytest-trio in the repo
    %python3_test pytest3 -v -k 'not test_strict_mode_ignores_trio_fixtures'
