name       : python-pytest-asyncio
version    : 0.21.1
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-asyncio/pytest-asyncio-0.21.1.tar.gz : 40a7eae6dded22c7b604986855ea48400ab15b069ae38116e8c01238e9eeb64d
homepage   : https://github.com/pytest-dev/pytest-asyncio
license    : Apache-2.0
component  : programming.python
summary    : Pytest support for asyncio
description: |
    pytest-asyncio is an Apache2 licensed library, written in Python, for testing asyncio code with pytest. asyncio code is usually written in the form of coroutines, which makes it slightly more difficult to test using normal testing tools. pytest-asyncio provides useful fixtures and markers to make testing easier.
builddeps  :
    - python-async-generator # check
    - python-build
    - python-flaky           # check
    - python-hypothesis      # check
    - python-installer
    - python-pytest          # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # we don't have python-pytest-trio in the repo
    %python3_test pytest -v -k 'not test_strict_mode_ignores_trio_fixtures'
