name       : python-pytest-asyncio
version    : 0.18.3
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-asyncio/pytest-asyncio-0.18.3.tar.gz : 7659bdb0a9eb9c6e3ef992eef11a2b3e69697800ad02fb06374a210d85b29f91
homepage   : https://github.com/pytest-dev/pytest-asyncio
license    : Apache-2.0
component  : programming.python
summary    : Pytest support for asyncio
description: |
    pytest-asyncio is an Apache2 licensed library, written in Python, for testing asyncio code with pytest. asyncio code is usually written in the form of coroutines, which makes it slightly more difficult to test using normal testing tools. pytest-asyncio provides useful fixtures and markers to make testing easier.
builddeps  :
    - python-async-generator
    - python-flaky
    - python-hypothesis
    - python-pytest
    - python-setuptools-scm
rundeps    :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # we don't have pytest-trio in the repo
    %python3_test pytest3 -v -k 'not test_strict_mode_ignores_trio_fixtures'
